name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # O cambia a 'master' si esa es tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            #Probando

            # Detener el proceso si existe, pero no fallar si no existe
            pm2 stop trade-crypto || true
            
            cd /var/www/html/Trade-Crypto
            
            # Descargar los últimos cambios
            git pull origin main
            
            # Instalar nuevas dependencias si las hay (usando npm si pnpm no está en el VPS)
            pnpm install || npm install
            
            # Compilar el código
            npm run build
            
            # Iniciar o reiniciar PM2
            pm2 restart trade-crypto || pm2 start dist/index.js --name trade-crypto
            
            # Guardar la configuración de PM2
            pm2 save
